// flow-typed signature: 98e792f4fd0a1e8cbff35753eedff73f
// flow-typed version: <<STUB>>/apptentive-react-native_v5.5.0/flow_v0.105.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apptentive-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apptentive-react-native' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apptentive-react-native/js' {
  declare module.exports: any
}

declare module 'apptentive-react-native/js/platform-specific.android' {
  declare module.exports: any
}

declare module 'apptentive-react-native/js/platform-specific.ios' {
  declare module.exports: any
}

// Filename aliases
declare module 'apptentive-react-native/js/index' {
  declare module.exports: $Exports<'apptentive-react-native/js'>
}
declare module 'apptentive-react-native/js/index.js' {
  declare module.exports: $Exports<'apptentive-react-native/js'>
}
declare module 'apptentive-react-native/js/platform-specific.android.js' {
  declare module.exports: $Exports<
    'apptentive-react-native/js/platform-specific.android'
  >
}
declare module 'apptentive-react-native/js/platform-specific.ios.js' {
  declare module.exports: $Exports<
    'apptentive-react-native/js/platform-specific.ios'
  >
}
